In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
import numpy as np

sys.path.append("../")

In [3]:
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd
import seaborn as sns
import torch

from aggregate_results import agg_all_results, agg_mil_results, agg_rlmil_results, add_formatted_column, save_dataset_table

# Regression Results

In [4]:
data_path = '../data'
model_path = '../dev_models'
bag_embedding_column_name = "bag_embeddings"

task_type = 'regression'
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

regression_results = agg_results(device=device, data_dir_path=data_path, models_dir_path=model_path,
                                 bag_embedded_column_name=bag_embedding_column_name, task_type=task_type)

RL-MIL json result does not exist! ../dev_models/regression/seed_0/political_data_with_age/text/roberta-base/old_age/bag_size_20/repset_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/political_data_with_age/text/roberta-base/old_age/bag_size_20/MaxMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/political_data_with_age/text/roberta-base/old_age/bag_size_20/AttentionMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/yourmorals_incas/timeline_cleaned_tweets/paraphrase-xlm-r-multilingual-v1/proportionality/bag_size_20/AttentionMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/authority/bag_size_20/MeanMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/authority/bag_size_20/repset_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/authority/bag_size_20/MaxMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/authority/bag_size_20/AttentionMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/purity/bag_size_20/MeanMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/purity/bag_size_20/repset_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/purity/bag_size_20/MaxMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/purity/bag_size_20/AttentionMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/loyalty/bag_size_20/MeanMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/loyalty/bag_size_20/repset_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/loyalty/bag_size_20/MaxMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/loyalty/bag_size_20/AttentionMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/care/bag_size_20/MeanMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/care/bag_size_20/repset_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/care/bag_size_20/MaxMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/care/bag_size_20/AttentionMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/fairness/bag_size_20/MeanMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/fairness/bag_size_20/repset_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/fairness/bag_size_20/MaxMLP_768_256_768
RL-MIL json result does not exist! ../dev_models/regression/seed_0/facebook/text/roberta-base/fairness/bag_size_20/AttentionMLP_768_256_768

In [5]:
regression_results

,model,embedding_model,bag_size,dataset,label,seed,test/loss,test/r2,test/avg-r2,test/ensamble-r2
0,MeanMLP,twhin-bert-base,20,incas,authority,0,0.845173,-0.053972,NaN,NaN
1,rl-MeanMLP,twhin-bert-base,20,incas,authority,0,0.772702,NaN,0.032192,0.052606
2,repset,twhin-bert-base,20,incas,authority,0,0.845856,-0.054824,NaN,NaN
3,rl-repset,twhin-bert-base,20,incas,authority,0,0.789110,NaN,0.016024,0.047248
4,MaxMLP,twhin-bert-base,20,incas,authority,0,0.844142,-0.052687,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
259,AttentionMLP,roberta-base,20,facebook,care,0,0.622964,0.021919,NaN,NaN
260,MeanMLP,roberta-base,20,facebook,fairness,0,0.595369,0.039048,NaN,NaN
261,repset,roberta-base,20,facebook,fairness,0,0.598940,0.033284,NaN,NaN
262,MaxMLP,roberta-base,20,facebook,fairness,0,0.609578,0.016115,NaN,NaN
263,AttentionMLP,roberta-base,20,facebook,fairness,0,0.582935,0.059118,NaN,NaN

# Classification results

In [6]:
data_path = '../data'
model_path = '../dev_models'
bag_embedding_column_name = "bag_embeddings"

task_type = 'classification'
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

classification_results = agg_results(device=device, data_dir_path=data_path, models_dir_path=model_path,
                                      bag_embedded_column_name=bag_embedding_column_name, task_type=task_type)

In [7]:
classification_results

,model,embedding_model,bag_size,dataset,label,seed,test/loss,test/accuracy,test/precision,test/recall,test/f1,test/avg-f1,test/ensamble-f1
0,MeanMLP,twhin-bert-base,20,incas,ladder,0,1.005532,0.553571,0.522013,0.340278,0.286576,NaN,NaN
1,rl-MeanMLP,twhin-bert-base,20,incas,ladder,0,1.074699,NaN,NaN,NaN,NaN,0.401599,0.431973
2,repset,twhin-bert-base,20,incas,ladder,0,1.008471,0.464286,0.454167,0.409722,0.395833,NaN,NaN
3,rl-repset,twhin-bert-base,20,incas,ladder,0,1.017148,NaN,NaN,NaN,NaN,0.436105,0.456790
4,MaxMLP,twhin-bert-base,20,incas,ladder,0,1.123382,0.517857,0.294785,0.336806,0.296296,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,rl-repset,camembert-base,20,incas,religion,0,0.766325,NaN,NaN,NaN,NaN,0.605050,0.608369
138,MaxMLP,camembert-base,20,incas,religion,0,0.695370,0.457627,0.556548,0.511072,0.360434,NaN,NaN
139,rl-MaxMLP,camembert-base,20,incas,religion,0,0.693518,NaN,NaN,NaN,NaN,0.396614,0.396279
140,AttentionMLP,camembert-base,20,incas,religion,0,0.650854,0.610169,0.625595,0.622960,0.609721,NaN,NaN
141,rl-AttentionMLP,camembert-base,20,incas,religion,0,0.660180,NaN,NaN,NaN,NaN,0.648657,0.628708

# Tables

In [9]:
classification_results = add_formatted_column(classification_results, 'f1')
classification_results

,model,embedding_model,dataset,label,avg_f1,std_f1,formatted_f1,std_avg_f1,avg_ensamble_f1,std_ensamble_f1
0,AttentionMLP,camembert-base,incas,age,0.232021,NaN,$0.232_{(\pm nan)}$,NaN,NaN,NaN
1,AttentionMLP,camembert-base,incas,education,0.500240,NaN,$0.500_{(\pm nan)}$,NaN,NaN,NaN
2,AttentionMLP,camembert-base,incas,ethnicity,0.295215,NaN,$0.295_{(\pm nan)}$,NaN,NaN,NaN
3,AttentionMLP,camembert-base,incas,ladder,0.258436,NaN,$0.258_{(\pm nan)}$,NaN,NaN,NaN
4,AttentionMLP,camembert-base,incas,political_orientation,0.216867,NaN,$0.217_{(\pm nan)}$,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
66,rl-repset,twhin-bert-base,incas,education,0.437799,NaN,$0.438_{(\pm nan)}$ / $0.479_{(\pm nan)}$,NaN,0.479237,NaN
67,rl-repset,twhin-bert-base,incas,ethnicity,0.208634,NaN,$0.209_{(\pm nan)}$ / $0.207_{(\pm nan)}$,NaN,0.206909,NaN
68,rl-repset,twhin-bert-base,incas,ladder,0.436105,NaN,$0.436_{(\pm nan)}$ / $0.457_{(\pm nan)}$,NaN,0.456790,NaN
69,rl-repset,twhin-bert-base,incas,political_orientation,0.320560,NaN,$0.321_{(\pm nan)}$ / $0.323_{(\pm nan)}$,NaN,0.323103,NaN
70,rl-repset,twhin-bert-base,incas,religion,0.644733,NaN,$0.645_{(\pm nan)}$ / $0.725_{(\pm nan)}$,NaN,0.724942,NaN

In [10]:
regression_results = add_formatted_column(regression_results, 'r2')
regression_results

,model,embedding_model,dataset,label,avg_r2,std_r2,formatted_r2,std_avg_r2,avg_ensamble_r2,std_ensamble_r2
0,AttentionMLP,camembert-base,incas,authority,0.049305,NaN,$0.049_{(\pm nan)}$,NaN,NaN,NaN
1,AttentionMLP,camembert-base,incas,care,-0.008185,NaN,$-0.008_{(\pm nan)}$,NaN,NaN,NaN
2,AttentionMLP,camembert-base,incas,equality,-0.025439,NaN,$-0.025_{(\pm nan)}$,NaN,NaN,NaN
3,AttentionMLP,camembert-base,incas,loyalty,-0.136984,NaN,$-0.137_{(\pm nan)}$,NaN,NaN,NaN
4,AttentionMLP,camembert-base,incas,proportionality,-0.074291,NaN,$-0.074_{(\pm nan)}$,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
115,rl-repset,twhin-bert-base,yourmorals_incas,care,0.077431,NaN,$0.077_{(\pm nan)}$ / $0.087_{(\pm nan)}$,NaN,0.086523,NaN
116,rl-repset,twhin-bert-base,yourmorals_incas,equality,-0.093674,NaN,$-0.094_{(\pm nan)}$ / $-0.035_{(\pm nan)}$,NaN,-0.035486,NaN
117,rl-repset,twhin-bert-base,yourmorals_incas,loyalty,0.200482,NaN,$0.200_{(\pm nan)}$ / $0.211_{(\pm nan)}$,NaN,0.211478,NaN
118,rl-repset,twhin-bert-base,yourmorals_incas,proportionality,0.092883,NaN,$0.093_{(\pm nan)}$ / $0.100_{(\pm nan)}$,NaN,0.099838,NaN
119,rl-repset,twhin-bert-base,yourmorals_incas,purity,0.232199,NaN,$0.232_{(\pm nan)}$ / $0.245_{(\pm nan)}$,NaN,0.245436,NaN

In [11]:
classification_results.dataset.unique()

array(['incas'], dtype=object)

In [12]:
save_dataset_table(classification_results, 'incas', 'f1', 'classification')

In [13]:
regression_results.dataset.unique()

array(['incas', 'yourmorals_incas', 'facebook', 'political_data_with_age'],
      dtype=object)

In [14]:
save_dataset_table(regression_results, 'political_data_with_age', 'r2', 'regression')